'use client';
import {useState} from 'react';
import type {Session} from '@/lib/ui-types';
type Member={id:string;name:string;team:string;courseSection:string;role:string;locked:boolean};
export default function AccountPanel({session,onSession,onClose}:{session:Session|null;onSession:(s:Session)=>void;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[members,setMembers]=useState<Member[]|null>(null);
 async function request(path:string,body?:unknown,method='POST'){const r=await fetch(path,body?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="minimal-overlay"><section className="minimal-dialog" role="dialog" aria-modal="true" aria-label="Account"><button className="dialog-close" aria-label="Close account" onClick={onClose}>×</button><h2>{session?.user?session.registered?'Your account':'Complete your registration':'Sign in to Common Ground'}</h2>
 {session?.localPreview&&<p className="notice amber"><b>Local simulation only.</b> This preview uses one shared test identity. It does not verify your ChatGPT account or email. Published Sites authentication must be tested separately.</p>}
 {error&&<p role="alert">{error}</p>}
 {!session?<p>Checking sign-in status…</p>:!session.user?<><p>Browse the design and evidence without an account. To use the adviser, sign in with ChatGPT, then register your course section and team.</p><a className="button primary" href="/signin-with-chatgpt?return_to=/" target="_top">{session.localPreview?'Continue with local test identity':'Sign in with ChatGPT'}</a><p className="caption">Sites supplies your identity. This website does not ask for your ChatGPT password or an API key.</p></>:!session.registered?<><p>Signed in as <b>{session.user.email}</b>. Identity and email come from Sites; filling out this form does not change who is signed in.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{await request('/api/register',{name:f.get('name'),courseSection:f.get('courseSection'),team:f.get('team'),agreeToRules:f.get('agreeToRules')==='on'});onSession(await request('/api/session'))})}}><label>Name<input name="name" defaultValue={session.user.name||session.user.displayName} required maxLength={100}/></label><label>Course section<input name="courseSection" defaultValue={session.user.courseSection||''} required maxLength={100} placeholder="Your course section"/></label><label>Team<input name="team" defaultValue={session.user.team||''} required maxLength={100} placeholder="Your project team"/></label><h3>Project rules</h3><ul><li>Use this site for the course’s initial-design evaluation.</li><li>Distinguish evidence from assumptions and do not claim professional certification.</li><li>Do not submit confidential research data or other people’s personal information to the adviser.</li></ul><label className="registration-agreement"><input type="checkbox" name="agreeToRules" required/> I agree to these project rules.</label><button disabled={busy}>{busy?'Saving…':'Complete registration'}</button></form><a href="/signout-with-chatgpt?return_to=/" target="_top">Use a different account / Sign out</a></>:<><p><b>{session.user.name||session.user.displayName}</b><br/>{session.user.email}</p><dl className="mini-metrics"><div><dt>Course section</dt><dd>{session.user.courseSection}</dd></div><div><dt>Team</dt><dd>{session.user.team}</dd></div><div><dt>Access</dt><dd>{session.role==='viewer'?'Registered user':session.role}</dd></div></dl><p>{session.role==='admin'?'You can use the adviser, maintain evidence, modify the shared design and assign project roles.':session.role==='editor'?'You can use the adviser and maintain evidence. Shared design changes and role assignments require an administrator.':'You can use the adviser. Evidence changes require an editor; shared design changes require an administrator.'}</p><p className="caption">Your registration is saved against your Sites user ID. Future sign-ins reuse this profile.</p>
 {session.role==='admin'&&<section><h3>Project member roles</h3><p className="caption">Roles apply to this shared consortium project. A self-entered team name does not grant access.</p><button disabled={busy} onClick={()=>act(async()=>setMembers((await request('/api/roles')).users))}>Load registered members</button>{members?.map(m=><div key={m.id}><label>{m.name} · {m.team}<select aria-label={`Role for ${m.name}`} value={m.role} disabled={busy||m.locked} onChange={e=>{const role=e.target.value;act(async()=>{await request('/api/roles',{userId:m.id,role},'PATCH');setMembers((await request('/api/roles')).users)})}}><option value="viewer">Registered user</option><option value="editor">Editor</option><option value="admin">Team administrator</option></select></label>{m.locked&&<small>Protected administrator / own role</small>}</div>)}</section>}
 <div className="mini-links"><button onClick={onClose}>Continue to dashboard</button><a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></div></>}
 </section></div>
}
