'use client';
import type {ModelInputs} from '@/lib/model';
import {runScenarios} from '@/lib/model';
import type {Requirements} from '@/lib/requirements';
import {demandCapacity} from '@/lib/requirements';
export default function CommitteeDashboard({inputs,requirements,version,onNavigate}:{inputs:ModelInputs;requirements:Requirements;version:string;onNavigate:(v:string)=>void}){
 const d=demandCapacity(requirements,inputs.utilization,inputs.productiveYield,inputs.gpuAllocatedItKw,inputs.pue);
 const rows=runScenarios(inputs), euro=(n:number)=>'€'+(n/1e6).toFixed(1)+'m';
 return <><div className="page-heading"><p className="section-context">University consortium · Investment committee</p><h1>Should we commit to a 25 MW facility?</h1><p>Formal proposal · {version}. Personal trials on the other pages do not change this assessment.</p></div>
 <div className="committee-grid"><section className="panel committee-verdict"><span className="badge amber-badge">Current screening recommendation</span><h2>Send back for more evidence</h2><p>Fund a bounded demand and site study before committing construction capital. Keep build, lease and phased hybrid under comparison.</p><ol><li>No signed long-term member computing commitments.</li><li>Grid delivery date, upgrade price and site permits remain unconfirmed.</li><li>Equipment and lease costs are planning assumptions, not executable offers.</li></ol><p><b>Preferred strategy and country: not established.</b> A lower model cost alone cannot resolve delivery risk.</p><button className="button primary" onClick={()=>onNavigate('design')}>Inspect requirements and costs →</button></section>
 <section className="panel"><h2>Current facility concept</h2><dl className="proposal-metrics"><div><dt>IT load · assumption</dt><dd>{inputs.itMw} MW</dd></div><div><dt>PUE · assumption</dt><dd>{inputs.pue}</dd></div><div><dt>Facility load · calculation</dt><dd>{(inputs.itMw*inputs.pue).toFixed(1)} MW</dd></div><div><dt>Full-load electricity · calculation</dt><dd>{(inputs.itMw*inputs.pue*8.76).toFixed(1)} GWh/year</dd></div></dl><p>{d?`Demand scenario implies ${d.facilityMw.toFixed(1)} MW. Inputs still require member and hardware validation.`:'Demand-derived capacity is unknown. Annual productive hours and peak concurrent demand are required.'}</p><p className="caption">20 MW IT × 1.25 PUE is the course starting point, not evidence of demand. Region and site are not selected.</p></section>
 <section className="panel"><h2>Three findings that could change the decision</h2><ol><li>Signed member GPU-hour and payment commitments, with peak workload benchmarks.</li><li>A deliverable grid offer: capacity, energization date, upgrade costs and permit feasibility.</li><li>Comparable build, equipment and lease bids, supported by site water and resilience assessments.</li></ol><button className="button secondary" onClick={()=>onNavigate('evidence')}>Inspect evidence →</button></section>
 <section className="panel"><h2>Investment readiness</h2>{[['Demand','Uncommitted'],['Grid and permits','Unknown'],['Economics','Model available · quotations missing'],['Technical concept','Preliminary · failure paths unvalidated'],['Governance','Proposed · not adopted'],['Water and local effects','Site assessment missing']].map(([a,b])=><div className="connection-row" key={a}><b>{a}</b><span>{b}</span></div>)}<p className="caption">Completing a calculation does not establish investment readiness.</p></section>
 <section className="panel"><h2>Who carries the risk?</h2><p><b>Grid delay:</b> proposed consortium exposure to committed capital and temporary leased capacity; negotiate delivery protections.</p><p><b>Demand loss:</b> owners retain fixed costs; lease minimums can also create obligations.</p><p><b>Member withdrawal:</b> agree exit payments and capacity reallocation before borrowing. Smaller members must not inherit uncapped liabilities.</p></section>
 <section className="panel"><h2>Alternatives and local effects</h2><p>Audit spare university capacity, commercial leases and distributed facilities against the same workloads before buying land.</p><p>Compare water availability, heat rejection, network paths, permits and grid-upgrade effects on other customers. National energy mix does not establish a facility’s contracted supply.</p><button className="button secondary" onClick={()=>onNavigate('explore')}>Compare candidate countries →</button></section></div>
 <section className="panel section-space"><h2>Formal proposal · nine financial scenarios</h2><p>Ten-year model; shared planning tariff. Facility and GPU capital are accounted for separately. Source: S-CALC.</p><div className="table-scroll"><table><thead><tr><th>Strategy / scenario</th><th>Before opening</th><th>Year 1 OPEX</th><th>€/productive GPU-hour</th><th>Capital at risk</th></tr></thead><tbody>{rows.map(r=><tr key={r.route+r.scenario}><th>{r.route} / {r.scenario==='delay'?'Grid delayed one year':r.scenario==='half'?'Half forecast utilization':'Baseline'}</th><td>{euro(r.preOpeningCash)}</td><td>{euro(r.annualOpex[0])}</td><td>{r.costPerGpuHour.toFixed(2)}</td><td>{euro(r.capitalAtRisk)}</td></tr>)}</tbody></table></div></section></>;
}
