'use client';
import {useState} from 'react';
import EuropeMap from './europe-map';
import type {Country} from '@/lib/ui-types';
export default function CountryMapSection({countries,onSource}:{countries:Country[];onSource:(id:string)=>void}){
 const [active,setActive]=useState('FR'),[extent,setExtent]=useState('europe'),[layer,setLayer]=useState('research');
 const country=countries.find(c=>c.code===active);if(!country)return null;
 return <section className="mini-card country-map-section"><h2>Explore the European context</h2><p>Browse the 27 EU country records. The committee comparison below retains Germany, France and Sweden; exploring the map does not change the team’s proposed location.</p><div className="map-controls"><label>Explore country<select value={active} onChange={e=>setActive(e.target.value)}>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label>Map extent<select value={extent} onChange={e=>setExtent(e.target.value)}><option value="europe">Europe</option><option value="world">World context</option></select></label><label>Map layer<select value={layer} onChange={e=>setLayer(e.target.value)}><option value="research">Committee shortlist</option><option value="price">Electricity price coverage</option></select></label></div><div className="country-map-layout"><div><EuropeMap countries={countries} selected={['DE','FR','SE']} active={active} onSelect={setActive} layer={layer} extent={extent}/><p className="caption">{layer==='price'?'Dark teal: price available · pale teal: price unavailable. Colours indicate availability, not price level.':'Dark teal: Germany, France and Sweden · pale teal: other EU records.'} Grey: outside dataset. Hover, tap or use keyboard focus to inspect. Map: Natural Earth; generalized boundaries.</p></div><aside className="map-country-brief" aria-label="Explored country details"><h3>{country.name}</h3><dl className="mini-metrics"><div><dt>Electricity reference</dt><dd>{country.price===null?'Unavailable':`€${country.price.toFixed(4)}/kWh`}</dd></div><div><dt>Price period</dt><dd>{country.pricePeriod||'Unknown'}</dd></div><div><dt>Carbon intensity</dt><dd>{country.carbonIntensity===null?'Unknown':`${country.carbonIntensity.toFixed(1)} gCO₂e/kWh`}</dd></div><div><dt>Energy year</dt><dd>{country.energyYear||'Unknown'}</dd></div><div><dt>Renewable generation</dt><dd>{country.renewableShare===null?'Unknown':`${country.renewableShare.toFixed(1)}%`}</dd></div></dl><p className="caption">National data provide context; they do not establish site grid capacity, cooling feasibility or a supplier offer.</p><div className="mini-links"><button onClick={()=>onSource('S-EUROSTAT')}>Electricity source</button><button onClick={()=>onSource('S-EMBER')}>Energy source</button></div></aside></div></section>
}
