"use client";
import {calculateModel,type ModelInputs,type Route,type Scenario} from '@/lib/model';
import {compareLocations,lowestCostOptions} from '@/lib/location-comparison';
import type {Country} from '@/lib/ui-types';
const names={build:'Build & own',lease:'Lease compute',hybrid:'Phased hybrid',base:'Base case',delay:'Grid delayed one year',half:'Half the utilization'};
const num=(v:number,d=1)=>v.toLocaleString('en-GB',{maximumFractionDigits:d});
const money=(v:number)=>`€${num(v/1e6)}m`;
export default function DecisionSummary({countries,inputs,scenario,route,onRoute,onDesign,onEvidence,focus,onFocus,budget,onBudget}:{countries:Country[];inputs:ModelInputs;scenario:Scenario;route:Route;onRoute:(r:Route)=>void;onDesign:()=>void;onEvidence:()=>void;focus:string;onFocus:(v:string)=>void;budget:string;onBudget:(v:string)=>void}){
 const country=countries.find(c=>c.code===focus)??countries[0];
 const ceiling=budget===''?null:Number(budget)*1e6;
 const rows=compareLocations(countries,inputs,scenario,ceiling),best=lowestCostOptions(rows);
 const option=rows.find(r=>r.country.code===country?.code)?.options.find(o=>o.route===route),r=option?.result;
 const demand=calculateModel(inputs,route,scenario).capacity;
 return <>
 <div className="page-heading"><h1>Choose a location and supply plan</h1><p>Your shortlisted countries, the same workload, and an explicit check of cost and evidence.</p></div>
 <section className="panel decision-brief"><div><h2>Demand carried from Design & costs</h2><p>{num(inputs.itMw)} MW IT · PUE {num(inputs.pue,2)} · {num(demand.gpuCount,0)} GPU equivalents · {num(demand.annualDemandGpuHours/1e6)}m productive GPU-hours/year</p><p className="caption">{names[scenario]}. National electricity references replace the illustrative tariff from page 2. All other inputs stay the same.</p></div><button className="button secondary" onClick={onDesign}>Edit demand & costs</button></section>
 <section className="panel decision-controls"><label className="field-label">Inspect country<select aria-label="Inspect candidate country" value={country?.code??''} onChange={e=>onFocus(e.target.value)}>{countries.map(c=><option value={c.code} key={c.code}>{c.name}</option>)}</select></label><label className="field-label">Supply plan<select aria-label="Summary supply plan" value={route} onChange={e=>onRoute(e.target.value as Route)}>{(['build','lease','hybrid'] as const).map(x=><option key={x} value={x}>{names[x]}</option>)}</select></label><label className="field-label">Opening budget ceiling · €m (optional)<input aria-label="Opening budget ceiling in million euros" type="number" min="0" step="10" value={budget} placeholder="No ceiling specified" onChange={e=>onBudget(e.target.value===''?'':String(Math.max(0,Number(e.target.value))))}/></label></section>
 <div className="summary-dashboard"><section className="panel recommendation-card"><span className="badge amber-badge">Conditional assessment</span><h2>{!r?'Insufficient price evidence':option?.withinBudget===false?'Outside your opening budget':'Worth investigating further'}</h2><p><b>{country?.name} · {names[route]}</b></p><p>{!r?'No usable national reference tariff is available. We do not borrow another country’s price or rank this location. Get a site tariff or comparable supplier quote.':option?.withinBudget===false?`Opening cash of ${money(r.preOpeningCash)} exceeds your ${money(ceiling!)} ceiling. This plan does not fit that funding constraint; change the route or capacity.`:ceiling===null?'The model can allocate the assumed workload, but you have not set a budget ceiling. Affordability and actual delivery capacity remain unverified.':'The model fits your opening budget and allocates the assumed workload. This is a candidate for due diligence, not an approved construction or supply decision.'}</p><p className="caption">No candidate is confirmed ready to build: grid capacity, availability, permits and supplier commitments are not established.</p></section>
 <section className="panel"><h2>Lowest modeled unit cost</h2>{best.length?<><p>{best.map(x=>`${x.country.name} / ${names[x.route]}`).join(' · ')}</p><p><b>€{num(best[0].result!.costPerGpuHour,2)} / productive GPU-hour</b></p><p className="caption">Minimum across all three routes and candidates with a usable tariff{ceiling!==null?', subject to your opening budget':''}. Equal outcomes stay tied. This is a cost screen, not a weighted suitability ranking.</p></>:<p>No priced option fits the current screening conditions. Review missing prices or the budget ceiling.</p>}<p className="caption">Lease pricing is a common assumption across countries. A lease tie does not establish a preferred country or provider location.</p></section>
 <section className="panel"><h2>Budget for {country?.name}</h2>{r?<dl className="proposal-metrics"><div><dt>Cash before service</dt><dd>{money(r.preOpeningCash)}</dd></div><div><dt>Year 1 operating cost</dt><dd>{money(r.annualOpex[0])}</dd></div><div><dt>10-year model cost</dt><dd>{money(r.totalCost)}</dd></div><div><dt>Cost per productive GPU-hour</dt><dd>€{num(r.costPerGpuHour,2)}</dd></div></dl>:<p>Not calculated without a usable country tariff.</p>}<p className="caption">Construction, equipment, leasing and financing are shared estimates, not country-specific quotations. Sources: S-CALC and S-EUROSTAT.</p></section>
 <section className="panel"><h2>Resources and energy approach</h2><p>{route==='lease'?'Lease equivalent GPU capacity from a provider. Its location, electricity supply, cooling and service guarantees must be contracted.':`Own ${num(inputs.itMw*(route==='hybrid'?inputs.hybridBuildFraction:1))} MW of IT capacity with grid electricity, UPS, standby generation and proposed liquid cooling.${route==='hybrid'?' Lease the remaining workload.':''}`}</p><p>{r?`Year 1 modeled on-site electricity: ${num(r.capacity.annualEnergyGwh[0])} GWh.`:'On-site energy and cost details need a priced comparison.'} Leased-provider electricity is excluded from this on-site figure.</p><p>{country?.name} generation context: {num(country?.mix.renewables??0)}% renewable, {num(country?.mix.nuclear??0)}% nuclear, {num(country?.mix.fossil??0)}% fossil ({country?.energyYear}).</p><p className="caption">The national mix is context, not the facility’s contracted supply. No renewable PPA, hourly matching or provider emissions claim has been verified. Source: S-EMBER.</p></section>
 <section className="panel"><h2>Can this plan meet demand?</h2><ul className="summary-checks"><li><b>Model allocation:</b> {num(demand.annualDemandGpuHours/1e6)}m productive GPU-hours/year under {names[scenario].toLowerCase()}.</li><li><b>Hardware:</b> equivalent GPUs assumed; memory, interconnect and workload benchmarks need confirmation.</li><li><b>Power / provider:</b> grid connection date and capacity, or reserved lease capacity, are unconfirmed.</li><li><b>Resilience:</b> backup ratings, fuel, independent paths and recovery behavior remain unvalidated.</li></ul></section>
 <section className="panel"><h2>What would change the decision?</h2><p>Obtain member demand commitments, a site grid offer, comparable supplier bids and a local cooling / water assessment. Check permit and network constraints.</p><p>Test the grid-delay and half-utilization scenarios on the left. A lower cost only remains useful if the required capacity can actually be delivered.</p><button className="button secondary" onClick={onEvidence}>Review sources & gaps</button></section></div>
 <section className="panel table-panel summary-matrix"><h2>Same demand across {countries.length} countries × 3 supply plans</h2><p className="caption">Each cell: €/productive GPU-hour · cash before service. Click a priced cell to inspect its plan above. National tariffs are references, not site offers.</p><div className="table-scroll"><table><thead><tr><th>Country / reference tariff</th><th>Build & own</th><th>Lease compute</th><th>Phased hybrid</th></tr></thead><tbody>{rows.map(row=><tr key={row.country.code}><th>{row.country.name}<small>{row.country.price===null?'No usable tariff':`€${row.country.price.toFixed(4)}/kWh · ${row.country.pricePeriod}`}</small></th>{row.options.map(o=><td key={o.route}>{o.result?<button className="table-link" aria-pressed={country?.code===row.country.code&&route===o.route} onClick={()=>{onFocus(row.country.code);onRoute(o.route)}}>€{num(o.result.costPerGpuHour,2)}<small>{money(o.result.preOpeningCash)} opening</small>{o.withinBudget===false&&<small>Exceeds budget</small>}</button>:<span>Not ranked</span>}</td>)}</tr>)}</tbody></table></div></section>
 </>;
}
