'use client';
import {useState,useEffect} from 'react';
import MetricHelp,{CostDefinitions} from './metric-help';
import {caseDefaults,evaluateCase,type CaseControls} from '@/lib/minimal-case';
import type {Country} from '@/lib/ui-types';
import type {Route,Scenario} from '@/lib/model';
const names={build:'Build & own',lease:'Lease compute',hybrid:'Phased hybrid',base:'Base case',delay:'Grid delayed one year',half:'Half forecast utilization'};
const routes:Route[]=['build','lease','hybrid'];
const num=(v:number)=>v.toLocaleString('en-GB',{maximumFractionDigits:2});
const money=(v:number)=>`€${num(v/1e6)}m`;
function NumberInput({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){
 const [draft,setDraft]=useState(String(value));
 useEffect(()=>setDraft(String(value)),[value]);
 const invalid=draft===''||!Number.isFinite(Number(draft))||Number(draft)<min||Number(draft)>max||(step===1&&!Number.isInteger(Number(draft)));
 return <label>{label}<input type="number" value={draft} min={min} max={max} step={step} aria-invalid={invalid} onChange={e=>{setDraft(e.target.value);const n=Number(e.target.value);if(e.target.value!==''&&Number.isFinite(n)&&n>=min&&n<=max&&(step!==1||Number.isInteger(n)))onChange(n)}}/>{invalid&&<small role="status">Enter {num(min)}–{num(max)}. Results retain the last valid value.</small>}</label>;
}
export default function DemandDashboard({controls,onControls,c,countries,countryCode,onCountry,budget,onBudget,route,onRoute,scenario,onScenario,onDetail,error}:{
 controls:CaseControls;onControls:(c:CaseControls)=>void;c:ReturnType<typeof evaluateCase>;countries:Country[];countryCode:string;onCountry:(s:string)=>void;budget:string;onBudget:(s:string)=>void;route:Route;onRoute:(r:Route)=>void;scenario:Scenario;onScenario:(s:Scenario)=>void;onDetail:(view:string,section?:string)=>void;error:string;
}){
 const selected=c.results.find(r=>r.route===route&&r.scenario===scenario)!;
 const ceiling=budget===''?null:Number(budget)*1e6;
 const options=c.results.filter(r=>r.scenario===scenario);
 const affordable=options.filter(r=>ceiling===null||r.preOpeningCash<=ceiling);
 const best=[...affordable].sort((a,b)=>a.costPerGpuHour-b.costPerGpuHour)[0];
 return <><h1>What infrastructure does your demand need?</h1><p className="minimal-lead">Describe your workload. Compare the scale, cost and risks, then explore the evidence behind your summary.</p>
 <div className="demand-layout"><section className="mini-card demand-input-panel has-metric-help"><MetricHelp title="Your requirements"><p><b>Productive GPU-hours:</b> useful work by one equivalent GPU for one hour. For example, 100 GPUs doing useful work for 10 hours = 1,000 GPU-hours.</p><p><b>Peak concurrent GPUs:</b> the maximum GPUs needed at the same time, not the annual average.</p><p><b>Opening budget:</b> ceiling on year-0 cash, in millions of euros. It excludes later operations and equipment purchases.</p><p><b>Effective scheduling utilization:</b> useful GPU-hours ÷ available fleet-hours; used to size capacity and includes productive losses once.</p><p><b>Candidate country:</b> selects the national reference electricity tariff; other cost assumptions remain shared estimates.</p></MetricHelp><span className="eyebrow">01 · Your requirements</span><h2>Start with your demand</h2>
 <NumberInput label="Productive GPU-hours / year" value={controls.annualHours} min={1000000} max={87600000} step={1000000} onChange={annualHours=>onControls({...controls,annualHours})}/>
 <NumberInput label="Peak concurrent GPUs" value={controls.peakGpus} min={1} max={10000} step={1} onChange={peakGpus=>onControls({...controls,peakGpus})}/>
 <label>Candidate country<select value={countryCode} onChange={e=>onCountry(e.target.value)}>{countries.map(co=><option key={co.code} value={co.code}>{co.name}</option>)}</select></label>
 <label>Opening budget ceiling · €m (optional)<input type="number" min="0" max="100000" value={budget} placeholder="No ceiling specified" onChange={e=>{const v=e.target.value;if(v===''||(Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=100000))onBudget(v)}}/></label>
 <p className="caption">The budget covers cash before opening, not ten-year spending. These are unverified user assumptions for equivalent GPUs; hardware and workload benchmarks still matter.</p>
 <details><summary>Advanced assumptions</summary><NumberInput label="Effective scheduling utilization" value={controls.utilization} min={.1} max={1} step={.05} onChange={utilization=>onControls({...controls,utilization})}/><NumberInput label="PUE" value={controls.pue} min={1} max={2} step={.05} onChange={pue=>onControls({...controls,pue})}/><p className="caption">{c.inputs.gpuAllocatedItKw} kW allocated IT per GPU. Effective utilization includes productive losses once.</p><button onClick={()=>onDetail('design','assumptions')}>All calculation assumptions →</button></details>
 <button onClick={()=>onControls(caseDefaults)}>Use example demand</button>{error&&<p role="alert">{error} Results retain the last supported inputs.</p>}
 </section><section className="mini-card has-metric-help"><MetricHelp title="Estimated scale"><p><b>Equivalent GPUs:</b> round up the larger of peak concurrent GPUs and annual productive GPU-hours ÷ (8,760 × effective scheduling utilization).</p><p><b>IT capacity (MW):</b> GPU count × {c.inputs.gpuAllocatedItKw} kW allocated per GPU ÷ 1,000. Allocated IT power includes hosts, networking and storage.</p><p><b>PUE:</b> total facility power ÷ IT power. Total facility capacity = IT MW × PUE.</p><p><b>Annual full-load electricity (GWh):</b> total facility MW × 8,760 ÷ 1,000. This assumes continuous full load; modeled operating electricity accounts for utilization and idle power.</p><p><b>Reference share:</b> required GPUs ÷ GPUs in the fixed 20 MW IT reference × 100%.</p></MetricHelp><span className="eyebrow">02 · Your estimated scale</span><h2>{num(c.requiredMw)} MW total facility capacity</h2><div className="minimal-kpis"><div><b>{num(c.requiredGpus)}</b><span>Equivalent GPUs · calculated</span></div><div><b>{num(c.requiredItMw)} MW</b><span>IT capacity · calculated</span></div><div><b>{num(c.requiredMw*8.76)} GWh</b><span>Annual full-load electricity</span></div><div><b>{controls.pue}</b><span>PUE · assumption</span></div></div>
 <p>Capacity covers both peak concurrency and annual GPU-hours at the assumed scheduling utilization. All three supply plans serve the same workload.</p>
 <div className="demand-reference"><b>Course reference: 25 MW</b><p>20 MW IT × 1.25 PUE · 219 GWh/year at full load.</p><p>{c.capacityFits?`${num(c.requiredGpus/c.referenceGpus*100)}% of the reference GPU fleet is required by these assumptions.`:'Demand exceeds the reference GPU fleet; a 25 MW baseline does not meet this capacity screen.'} Your plan is sized separately and uses PUE {controls.pue}.</p></div>
 <button onClick={()=>onDetail('design','sizing')}>Why this size? →</button>
 </section></div>
 <section className="mini-section"><div className="mini-section-heading"><div><span className="eyebrow">03 · Your supply options</span><h2>Same demand, different commitments</h2></div><label>Analysis scenario<select value={scenario} onChange={e=>onScenario(e.target.value as Scenario)}>{(['base','delay','half'] as Scenario[]).map(s=><option key={s} value={s}>{names[s]}</option>)}</select></label></div>
 <p>{best?`Lowest modeled unit cost${ceiling===null?'': ' within your opening budget'}: ${names[best.route]}.`:'No option fits your opening budget.'} {ceiling===null?'No budget ceiling specified.':'Budget fit does not establish financing or delivery readiness.'}</p>
 <div className="minimal-three">{options.map(v=><section className={`mini-card supply-option has-metric-help ${route===v.route?'selected-option':''}`} key={v.route}><MetricHelp title={`${names[v.route]} metrics`}><CostDefinitions/></MetricHelp><h3>{names[v.route]}</h3><p>{v.route==='lease'?'Lease equivalent capacity; provider availability remains unconfirmed.':`Own ${num(v.capacity.ownedItMw)} MW IT${v.route==='hybrid'?' and lease the remaining workload':''}.`}</p><dl className="mini-metrics"><div><dt>Cash before opening</dt><dd>{money(v.preOpeningCash)}</dd></div><div><dt>Year 1 operating cost</dt><dd>{money(v.annualOpex[0])}</dd></div><div><dt>Cost / productive GPU-hour</dt><dd>€{v.costPerGpuHour.toFixed(2)}</dd></div><div><dt>Capital at risk</dt><dd>{money(v.capitalAtRisk)}</dd></div></dl><p className="caption">{ceiling===null?'Budget not specified':v.preOpeningCash<=ceiling?'Within opening budget':'Exceeds opening budget'}</p><button aria-pressed={route===v.route} onClick={()=>onRoute(v.route)}>{route===v.route?'Selected for analysis':'Inspect this plan'}</button></section>)}</div>
 <button onClick={()=>onDetail('design','cash-flow')}>Why these costs? →</button></section>
 <section className="mini-card has-metric-help"><MetricHelp title="Stress cases"><p><b>Base case:</b> your current demand and cost assumptions.</p><p><b>Grid delayed one year:</b> owned-site GPU purchases move to year 1; temporary leased compute supplies the owned share in that year. Facility capital and fixed costs remain. Pure leasing is unchanged.</p><p><b>Half forecast utilization:</b> half the productive GPU-hours with the same installed fleet and capital. Power retains an idle floor and lease minimums still apply.</p><p><b>On-site electricity:</b> owned IT MW × [idle power share + (1 − idle share) × scenario utilization] × PUE × 8,760 ÷ 1,000. Zero for pure leasing and during the modeled grid-delay year; provider electricity is excluded.</p><p>Unit cost divides ten-year net cost by productive hours. Capital at risk includes capital less recovery plus modeled lease commitments.</p></MetricHelp><span className="eyebrow">04 · Risk & evidence</span><h2>{names[route]} under stress</h2><div className="minimal-three">{(['base','delay','half'] as Scenario[]).map(s=>{const v=c.results.find(r=>r.route===route&&r.scenario===s)!;return <article key={s}><h3>{names[s]}</h3><p><b>€{v.costPerGpuHour.toFixed(2)}</b> / productive GPU-hour</p><p>{money(v.capitalAtRisk)} capital at risk</p></article>})}</div><p className="caption">Stress tests keep the demand-sized fleet fixed. Grid delay assumes temporary leased capacity is available. Year 1 on-site electricity for the selected scenario: {num(selected.capacity.annualEnergyGwh[0])} GWh; leased-provider energy is excluded.</p><p>Demand commitments, grid delivery, supplier bids and local water / backup performance remain unverified. Cost estimates do not establish investment readiness.</p><div className="mini-links"><button onClick={()=>onDetail('design','resilience')}>Power and failure paths →</button><button onClick={()=>onDetail('explore')}>Why this country? →</button><button onClick={()=>onDetail('evidence')}>Check sources →</button></div></section>
 </>;
}
