import {teamConclusion} from '@/lib/team-conclusion';
export default function DesignRationale({itMw,facilityMw,pue}:{itMw:number;facilityMw:number;pue:number}){
 const n=(v:number)=>v.toLocaleString('en-GB',{maximumFractionDigits:2});
 return <>
 <section className="mini-card"><h2>How workload requirements shape the leased service</h2><div className="table-scroll"><table><thead><tr><th>Requirement / evidence</th><th>Proposed response and reason</th><th>What must be confirmed</th></tr></thead><tbody>
 <tr><th>Capacity · project baseline</th><td>The project uses {n(itMw)} MW of IT load as a comparison baseline. At assumed PUE {pue}, facility power is {n(facilityMw)} MW. Use workload benchmarks to specify equivalent leased service; do not infer a dedicated provider facility from this reference.</td><td>Equipment specifications and member commitments still require validation. The project scope fixes capacity at 20 MW IT.</td></tr>
 <tr><th>France / Paris-Saclay · local design context</th><td>The comparison supports France on reference electricity cost. Jean Zay provides a regional warm-water cooling and heat-recovery example (S-FR-COOL), supporting investigation of those interfaces.</td><td>A French national tariff does not secure a 25 MW grid connection. Confirm local grid delivery, water conditions and a heat customer; no heat-reuse revenue is assumed.</td></tr><tr><th>Cooling · concentrated GPU heat</th><td>Direct-to-chip liquid cooling is the candidate for dense training racks. A coolant loop moves heat to outdoor dry heat rejection; residual air-cooled equipment still needs room cooling. Dry rejection limits routine evaporative water dependence.</td><td>GPU/rack specification, heat density, vendor temperatures, summer performance, pumping and water use. Total MW alone does not require liquid cooling. PUE {pue} is a target assumption, not a calculated benefit. No heat-reuse income is counted.</td></tr>
 <tr><th>Internal network · multi-node training</th><td>A high-bandwidth, low-latency compute fabric carries GPU-to-GPU training traffic. Shared parallel storage serves data and checkpoints; separate management access supports monitoring and recovery.</td><td>Benchmark actual jobs before choosing Ethernet/RDMA or InfiniBand, topology, bandwidth and storage throughput. Independent single-GPU jobs may need less interconnect capacity.</td></tr>
 <tr><th>External network · university access</th><td>Two physically diverse carrier paths connect member universities to the service. Identity-based access, project isolation and quotas govern shared use.</td><td>University connectivity, transfer volumes, route diversity and failure recovery. Two carrier contracts alone do not prove separate physical paths.</td></tr>
 <tr><th>Power · load and service continuity</th><td>{n(itMw)} MW IT × PUE {pue} = {n(facilityMw)} MW facility peak. Utility supply supports normal operation; UPS bridges transfer to generators. Independent A/B paths are proposed for protected load.</td><td>Grid offer, critical-load inventory, redundancy ratings, cooling restart, fuel and integrated failure tests. Training can checkpoint and be shed; protected services need agreed recovery targets.</td></tr>
 </tbody></table></div><p className="caption">Design decisions follow the assumed workload. Existing cooling examples demonstrate possible approaches, not feasibility at our new site. The system diagram describes infrastructure the provider must substantiate; the national comparison does not by itself determine equipment specifications.</p></section></>;
}

export function RecommendedSolution({itMw,facilityMw}:{itMw:number;facilityMw:number}){
 return <section className="mini-card recommendation"><span className="eyebrow">Recommended solution</span><h2>France first · lease GPU compute</h2><p>Seek equivalent GPU computing service from an existing provider, prioritizing France and retaining Sweden as an alternative. Provider bids must establish actual price, available capacity, location and service quality; national electricity prices do not determine lease prices.</p><p>The consortium manages member access, quotas, scheduling and data policies. The provider owns and operates GPUs, storage, internal networks, power and cooling. Verify workload performance, security and continuity before contracting.</p><p>The {itMw} MW IT / {facilityMw} MW facility case remains the comparison baseline. It is not a recommendation to purchase GPUs or build a new facility.</p></section>;
}
