import type {ModelResult} from '@/lib/model';
export default function DesignRequirements({result,pue}:{result:ModelResult;pue:number}){
 const mw=result.capacity.ownedItMw*pue;
 const n=(v:number)=>v.toLocaleString('en-GB',{maximumFractionDigits:2});
 return <section className="mini-card"><h2>Service requirements and failure design assumptions</h2><p>Planning assumptions for member review; no member has signed a service or purchase commitment.</p><div className="table-scroll"><table><thead><tr><th>Users</th><th>Timing and service</th><th>Security and allocation</th></tr></thead><tbody><tr><th>Large research training</th><td>Queueable multi-day jobs; checkpoints before interruption; peak GPU demand must be benchmarked as a single connected cluster.</td><td>Project isolation, controlled dataset access, encrypted storage and transfer. Regulated datasets require separate approval.</td></tr><tr><th>Teaching and smaller institutions</th><td>Reserve term-time class windows ahead of batch training; proposed 99.9% service availability target.</td><td>Guaranteed base quotas; unused reservations return to a common pool. No member can consume another member’s paid quota.</td></tr><tr><th>Inference and experiments</th><td>Protected service pool; latency, recovery time and recovery point targets require workload-owner agreement.</td><td>Identity-based access, audit logs and isolated service accounts; retention and backup policies to agree.</td></tr></tbody></table></div>
 <p>The 99.9% target permits {n(8760*.001)} hours of annual downtime, but is not yet demonstrated. Procurement depends on a utility energization milestone; there is no promised opening date.</p>
 <h3>Single-component loss and 48-hour outage</h3><p>For the owned portion ({n(mw)} MW peak including cooling), propose two independent electrical trains, each rated for 100% of critical load. Loss of the largest train leaves {n(mw)} MW only if the remaining train, transfer controls, UPS, generators and cooling all meet their ratings. Shared switchgear, fuel and control failures remain unresolved. If transfer fails, checkpoint and shed training first; preserve storage, network and teaching/inference only within demonstrated remaining capacity.</p>
 <p>Assume a 10-minute UPS bridge: usable AC energy requirement = {n(mw)} × 10/60 = {n(mw/6)} MWh, before battery aging and conversion margins. A 48-hour full-load outage requires {n(mw*48)} MWh from generators. An illustrative fuel sensitivity of 0.25 L/kWh implies {n(mw*48*1000*.25)} litres, before reserve. These assumptions do not establish tank size, autonomy or emissions compliance.</p>
 <p>No solar or wind firm capacity credit is taken. UPS energy is only credited for the transition interval. Verify hourly critical-load profiles, ambient derating, start reliability, protection coordination, integrated transfer tests, generator fuel curves, usable fuel stock, replenishment contracts, cooling restart and loss-of-carrier recovery before claiming uptime.</p>
 <h3>Cooling, water, network and storage</h3><p>Direct-to-chip liquid loops with dry heat rejection are proposed; heat reuse has no assumed revenue or guaranteed sink. At full IT load, a water-use sensitivity of 0.2–1.0 L/kWh would imply {n(result.capacity.ownedItMw*8760*.2)}–{n(result.capacity.ownedItMw*8760)} m³/year. This is a sensitivity range, not predicted water demand. Vendor WUE curves, local weather, makeup-water quality and discharge permissions are required.</p><p>Use two physically diverse external carriers, a benchmarked high-bandwidth cluster fabric, shared parallel storage and a separate backup copy. Bandwidth, storage volume, failure domains and recovery objectives remain procurement gates; allocated IT power includes their share. Lease contracts must meet the same workload and security requirements.</p>
 </section>
}
