"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Country } from '@/lib/ui-types';
type Feature={properties:{ISO_A2:string;NAME:string;LABEL_X:number;LABEL_Y:number};geometry:{type:string;coordinates:number[][][]|number[][][][]}};
// Mercator uses the same scale on both axes; high latitudes are clipped.
function project([lon,lat]:number[]){return [lon*Math.PI/180,-Math.log(Math.tan(Math.PI/4+Math.max(-80,Math.min(80,lat))*Math.PI/360))]}
function rings(f:Feature){return (f.geometry.type==='Polygon'?[f.geometry.coordinates as number[][][]]:f.geometry.coordinates as number[][][][]).flat()}
export default function EuropeMap({countries,selected,onSelect,layer,extent}:{countries:Country[];selected:string[];active:string;onSelect:(c:string)=>void;layer:string;extent:string}){
 const [features,setFeatures]=useState<Feature[]>([]),[error,setError]=useState(false),[hover,setHover]=useState<Feature|null>(null),[position,setPosition]=useState({x:20,y:20});
 useEffect(()=>{fetch('/world.geo.json').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{features:Feature[]}>}).then(g=>setFeatures(g.features)).catch(()=>setError(true))},[]);
 const canvas=useRef<HTMLDivElement>(null),[size,setSize]=useState({width:900,height:500});
 useEffect(()=>{if(!canvas.current)return;const observer=new ResizeObserver(([entry])=>setSize({width:entry.contentRect.width,height:entry.contentRect.height}));observer.observe(canvas.current);return()=>observer.disconnect()},[]);
 const world=extent==='world',width=Math.max(1,size.width),height=Math.max(1,size.height);
 const transform=useMemo(()=>{const a=project(world?[-180,80]:[-13,71.5]),b=project(world?[180,-60]:[36,34]);const scale=Math.min((width-30)/(b[0]-a[0]),(height-30)/(b[1]-a[1]));return(p:number[])=>{const[x,y]=project(p);return [Number((width/2+(x-(a[0]+b[0])/2)*scale).toFixed(2)),Number((height/2+(y-(a[1]+b[1])/2)*scale).toFixed(2))]}},[world,width,height]);
 const countryFor=(f:Feature)=>countries.find(c=>c.code===(f.properties.ISO_A2==='GR'?'EL':f.properties.ISO_A2));
 const locate=(e:React.MouseEvent<SVGPathElement>,f:Feature)=>{const rect=e.currentTarget.ownerSVGElement!.parentElement!.getBoundingClientRect();setPosition({x:Math.max(8,Math.min(e.clientX-rect.left+18,rect.width-274)),y:Math.max(8,Math.min(e.clientY-rect.top+18,rect.height-230))});setHover(f);const c=countryFor(f);if(c)onSelect(c.code)};
 const c=hover?countryFor(hover):undefined;
 return <div ref={canvas} className="map-canvas" onMouseLeave={()=>setHover(null)}>{error?<p className="notice">Map unavailable. Use the country filter to continue.</p>:<svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="xMidYMid meet" aria-label={`${world?'World':'Europe'} map with all EU countries highlighted; hover or focus for country details`}><defs><clipPath id="map-extent"><rect width={width} height={height}/></clipPath></defs><g clipPath="url(#map-extent)">{features.map((f,i)=>{const c=countryFor(f),isHovered=hover===f;const d=rings(f).map(r=>r.map((p,j)=>`${j?'L':'M'}${transform(p).join(',')}`).join(' ')+'Z').join(' ');return <path key={f.properties.ISO_A2+i} d={d} fill={isHovered?(c?'#126e78':'#b5c2c6'):!c?'#dce1e3':layer==='price'?(c.price===null?'#d3e9e4':'#398b86'):selected.includes(c.code)?'#398b86':'#a4d4c9'} stroke="#fff" strokeWidth={world?.55:1.1} className="map-country" tabIndex={c?0:undefined} role={c?'button':undefined} aria-label={c?`${c.name}, ${c.price===null?'price unavailable':`€${c.price.toFixed(4)} per kWh`}`:f.properties.NAME} onMouseEnter={e=>locate(e,f)} onMouseMove={e=>locate(e,f)} onFocus={()=>{setHover(f);setPosition({x:16,y:16});if(c)onSelect(c.code)}} onBlur={()=>setHover(null)} onClick={()=>{setHover(f);if(c)onSelect(c.code)}} onKeyDown={e=>{if(e.key==='Escape')setHover(null);if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setHover(f);onSelect(c.code)}}}/>})}</g></svg>}{hover&&<div className="map-tooltip" role="status" style={{left:position.x,top:position.y}}><strong>{c?.name??hover.properties.NAME}</strong>{c?<><dl><div><dt>Electricity · {c.pricePeriod}</dt><dd>{c.price===null?'Unavailable':`€${c.price.toFixed(4)} / kWh`}</dd></div><div><dt>Carbon intensity · {c.energyYear}</dt><dd>{c.carbonIntensity??'Unknown'} gCO₂e/kWh</dd></div><div><dt>Renewables · {c.energyYear}</dt><dd>{c.renewableShare??'Unknown'}%</dd></div><div><dt>Epoch cluster records</dt><dd>{c.clusterRecords}</dd></div></dl><small>National averages. Records are not a census.</small></>:<p>Outside the EU comparison scope.</p>}</div>}</div>
}
