import type {Country} from '@/lib/ui-types';
import {recommendationEvidence} from '@/lib/recommendation';
export default function LocationRecommendation({countries,energyGwh,compact=false}:{countries:Country[];energyGwh:number;compact?:boolean}){
 const e=recommendationEvidence(countries,energyGwh);
 const price=(c:Country|undefined)=>c?.price==null?'unavailable':`€${c.price.toFixed(4)}/kWh`;
 const carbon=(c:Country|undefined)=>c?.carbonIntensity==null?'unavailable':`${c.carbonIntensity.toFixed(1)} gCO₂e/kWh`;
 return <section className="mini-card recommendation"><span className="eyebrow">Country comparison → location recommendation</span><h2><strong>{e.supported?'France first choice, Sweden as alternative':'Location recommendation requires review'}</strong></h2>
 {!e.supported?<p>The displayed records are missing, use different periods, or no longer support the France-first reasoning. Reassess the shortlist before adopting the provisional France design.</p>:<><p>France has the lowest reference electricity price ({price(e.fr)}), with substantially lower generation carbon intensity than Germany. Sweden has lower carbon intensity ({carbon(e.se)} versus France’s {carbon(e.fr)}), at a slightly higher electricity reference ({price(e.se)}). We prioritize operating cost between these two low-carbon candidates and recommend France for the next site and supplier study.</p>
 {!compact&&<><p><b>Same construction scale in all three countries:</b> 20 MW IT × PUE 1.25 = 25 MW facility power; 25 × 8,760 = 219 GWh/year at continuous full load.</p><div className="minimal-three">{[e.fr,e.se,e.de].map(co=><article key={co!.code}><h3>{co!.name}</h3><p>Electricity at the current full-load reference: €{(co!.price!*energyGwh).toFixed(3)}m/year.</p><p>National generation carbon: {carbon(co)}.</p></article>)}</div><div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Decision and trade-off</th></tr></thead><tbody><tr><th>France · first choice</th><td>Lowest reference tariff; low-carbon national generation. Paris-Saclay’s Jean Zay cooling example supports investigating that region, but establishes no land, grid capacity or heat-network access for us.</td></tr><tr><th>Sweden · alternative</th><td>Lowest carbon intensity of the three. Prefer Sweden if carbon takes priority or a deliverable Swedish site/provider offer outweighs France’s small electricity advantage.</td></tr><tr><th>Germany · not first choice</th><td>Reference electricity is {price(e.de)} and carbon intensity is {carbon(e.de)}. Neither favors Germany in this screen. An earlier grid connection or better total service offer could still reverse the decision.</td></tr></tbody></table></div><p>At the same {energyGwh.toFixed(1)} GWh/year full-load reference, Sweden’s electricity premium over France is about €{((e.swedenPremium??0)/1e6).toFixed(3)}m/year; Germany’s is €{((e.germanyPremium??0)/1e6).toFixed(2)}m/year. These are electricity-only sensitivities, not annual operating forecasts or lease-price differences.</p><p><b>Decision rule:</b> at the fixed 20 MW IT / PUE 1.25 scale, national price and carbon narrow the shortlist; deliverable grid capacity, permits, network access, cooling and total supplier bids determine the actual site. No weighted score or confirmed site advantage is claimed. Facility counts and existing projects describe context and are not measures of spare capacity.</p></>}
 <p className="caption">Price: Eurostat, {e.fr?.pricePeriod} (S-EUROSTAT). Generation carbon: Ember, {e.fr?.energyYear} (S-EMBER). Regional example: S-FR-COOL. National averages do not specify a facility’s electricity contract. This is a conditional location recommendation, not construction approval. The committee should return the investment for demand commitments, a grid offer and comparable build/lease/hybrid bids. Site delivery is unknown in all three countries.</p></>}
 </section>;
}
