'use client';
import type {evaluateCommitteeCase,CaseControls} from '@/lib/minimal-case';
import type {Route} from '@/lib/model';
import MetricHelp,{CostDefinitions} from './metric-help';
const names={build:'Build & own',lease:'Lease compute',hybrid:'Phased hybrid',base:'Base case',delay:'Grid delayed one year',half:'Half forecast utilization'};
const num=(n:number)=>n.toLocaleString('en-GB',{maximumFractionDigits:2});
const money=(n:number)=>`€${num(n/1e6)}m`;
export default function TeamCase({c,controls,route,onRoute,onDetail,version,loaded}:{c:ReturnType<typeof evaluateCommitteeCase>;controls:CaseControls;route:Route;onRoute:(r:Route)=>void;onDetail:(page:string,section?:string)=>void;version:string;loaded:boolean}){
 const facilityMw=c.inputs.itMw*c.inputs.pue, annualGWh=facilityMw*8760/1000;
 return <><p className="eyebrow">Team committee case · 25 MW proposal</p><h1>Should the university consortium commit?</h1><p className="minimal-lead">France · Paris-Saclay study region. Provisional location; no parcel, grid offer or development approval confirmed.</p>
 <div className="overview-kpis">{[[num(c.inputs.itMw)+' MW','IT load'],[num(c.inputs.pue),'PUE assumption'],[num(facilityMw)+' MW','Total facility load'],[num(annualGWh)+' GWh','Annual energy · full load']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
 <section className="mini-card recommendation"><span className="eyebrow">Major decision</span><h2>Return for more evidence</h2><p>Validate demand and grid delivery before committing to a 25 MW build. Compare leased access and a smaller first phase with the original proposal.</p><p className="caption">Proposed concept: shared GPU infrastructure, UPS and standby generation, liquid cooling and diverse network paths. {loaded?'Stored assumptions':'Illustrative fallback'} · {version}.</p></section>
 <section className="mini-card"><h2>Three largest uncertainties</h2><div className="minimal-three uncertainty-grid"><article><span>01 · Demand</span><h3>Will members commit?</h3><p>No long-term compute or payment commitments. Obtain workload benchmarks and signed GPU-hour requirements.</p></article><article><span>02 · Delivery</span><h3>When can the site open?</h3><p>Grid capacity, upgrade cost, energization date and permits remain unconfirmed.</p></article><article><span>03 · Cost</span><h3>What will equivalent service cost?</h3><p>Obtain comparable construction, GPU and lease bids, including water and backup requirements.</p></article></div></section>
 <details className="mini-card disclosure"><summary>Does demand justify 25 MW? <span>{num(c.requiredMw)} MW indicated by current, uncommitted demand assumptions</span></summary><dl className="mini-metrics"><div><dt>Annual productive GPU-hours</dt><dd>{num(controls.annualHours)}</dd></div><div><dt>Peak concurrent GPUs</dt><dd>{num(controls.peakGpus)}</dd></div><div><dt>Scheduling utilization</dt><dd>{num(controls.utilization*100)}%</dd></div></dl><p>The smaller demand screen is a possible revision, not measured demand. {c.capacityFits?'The course-reference fleet covers this screening requirement.':'The course-reference fleet does not cover this screening requirement.'}</p><p>Original course reference: 20 MW IT × 1.25 PUE = 25 MW and 219 GWh/year. Current saved PUE is {c.inputs.pue}.</p><button onClick={()=>onDetail('design','sizing')}>View sizing calculation</button></details>
 <section className="mini-section"><span className="eyebrow">Compare the alternatives</span><h2>One workload, three supply commitments</h2><p>Build retains the 20 MW IT proposal. Lease buys equivalent productive compute. Hybrid owns {num(20*c.inputs.hybridBuildFraction)} MW IT and leases the residual workload. All use the same assumed annual demand.</p><div className="minimal-three">{c.results.filter(r=>r.scenario==='base').map(r=><section className="mini-card has-metric-help" key={r.route}><MetricHelp title={`${names[r.route]} metrics`}><CostDefinitions/></MetricHelp><h3>{names[r.route]}</h3><dl className="mini-metrics"><div><dt>Cash before opening</dt><dd>{money(r.preOpeningCash)}</dd></div><div><dt>Year 1 operating cost</dt><dd>{money(r.annualOpex[0])}</dd></div><div><dt>Cost / productive GPU-hour</dt><dd>€{r.costPerGpuHour.toFixed(2)}</dd></div><div><dt>Capital at risk</dt><dd>{money(r.capitalAtRisk)}</dd></div></dl><button aria-pressed={route===r.route} onClick={()=>onRoute(r.route)}>{route===r.route?'Currently viewed':'View this alternative'}</button></section>)}</div><p className="caption">Lowest modeled base-case unit cost: {names[c.best.route]}. This is a cost comparison, not the team’s final strategy recommendation. No formal budget ceiling or supplier commitment is established.</p></section>
 <section className="mini-card has-metric-help"><MetricHelp title="Stress-test outputs"><CostDefinitions/><p>Half utilization keeps purchased capacity fixed. Grid delay uses temporary leasing and delays GPU purchase; pure leasing is unchanged.</p></MetricHelp><h2>Stress tests · {names[route]}</h2><p>The focused alternative changes this detail view, not the three-way comparison or committee decision.</p><div className="table-scroll"><table><thead><tr><th>Scenario</th><th>Cash before opening</th><th>Year 1 OPEX</th><th>€/productive GPU-hour</th><th>Capital at risk</th></tr></thead><tbody>{c.results.filter(r=>r.route===route).map(r=><tr key={r.scenario}><th>{names[r.scenario]}</th><td>{money(r.preOpeningCash)}</td><td>{money(r.annualOpex[0])}</td><td>€{r.costPerGpuHour.toFixed(2)}</td><td>{money(r.capitalAtRisk)}</td></tr>)}</tbody></table></div><button onClick={()=>onDetail('summary','cash-flow')}>Inspect ten-year cash flows →</button></section>
 <section className="mini-card"><h2>Explore the supporting evidence</h2><p>Review location evidence and unresolved assumptions behind the team assessment.</p><div className="mini-links"><button onClick={()=>onDetail('explore')}>Compare three countries →</button><button onClick={()=>onDetail('evidence')}>Review evidence gaps →</button></div></section></>;
}
