import {test} from 'node:test';
import assert from 'node:assert/strict';
import {caseDefaults,evaluateCase,evaluateCommitteeCase} from '../lib/minimal-case';
test('demand sizes a 10 MW IT fleet and preserves a separate 25 MW reference',()=>{const c=evaluateCase(caseDefaults,.0614);for(const r of c.results.filter(r=>r.scenario==='base'))assert.equal(r.capacity.annualDemandGpuHours,caseDefaults.annualHours);assert.equal(c.requiredGpus,5000);assert.equal(c.inputs.itMw,10);assert.equal(c.requiredMw,12.5);assert.equal(c.referenceResults![0].capacity.peakFacilityMw,25);assert.equal(c.referenceResults![0].capacity.gpuCount,10000)});
test('lower annual demand and peak reduce fleet and capital together',()=>{const a=evaluateCase(caseDefaults,.0614),b=evaluateCase({...caseDefaults,annualHours:14000000,peakGpus:2500},.0614);assert.equal(b.inputs.itMw,a.inputs.itMw/2);assert.equal(b.results[0].preOpeningCash,a.results[0].preOpeningCash/2);assert.equal(b.results[0].capacity.annualDemandGpuHours,14000000)});
test('lower annual demand alone cannot shrink a fleet constrained by peak',()=>{const a=evaluateCase(caseDefaults,.0614),b=evaluateCase({...caseDefaults,annualHours:14000000},.0614);assert.equal(b.requiredGpus,a.requiredGpus);assert.equal(b.results[0].preOpeningCash,a.results[0].preOpeningCash)});
test('stress cases keep the newly sized fleet and capital, halving only productive output',()=>{const c=evaluateCase(caseDefaults,.0614);assert.equal(c.results[0].capacity.gpuCount,c.results[2].capacity.gpuCount);assert.equal(c.results[0].preOpeningCash,c.results[2].preOpeningCash);assert.equal(c.results[2].capacity.annualDemandGpuHours,14000000)});
test('scheduling ceiling can require more than the course reference without capping demand',()=>{const c=evaluateCase({...caseDefaults,utilization:.2},.0614);assert.equal(c.capacityFits,false);assert.ok(c.inputs.itMw>20);assert.equal(c.results[0].capacity.annualDemandGpuHours,28000000)});
test('PUE changes power and energy, not GPU sizing or course baseline',()=>{const a=evaluateCase(caseDefaults,.0614),b=evaluateCase({...caseDefaults,pue:1.5},.0614);assert.equal(b.requiredGpus,a.requiredGpus);assert.equal(b.requiredMw,15);assert.equal(b.baselineMw,25);assert.equal(b.referenceResults![0].capacity.peakFacilityMw,25)});
test('invalid requirements are rejected before they reach the financial model',()=>{for(const changes of [{annualHours:NaN},{peakGpus:1.5},{utilization:0},{annualHours:0}])assert.throws(()=>evaluateCase({...caseDefaults,...changes},.0614));});

test('committee review retains the original fleet while exposing a separate demand-sized revision',()=>{const c=evaluateCommitteeCase(caseDefaults,.0614);assert.equal(c.inputs.itMw,20);assert.equal(c.inputs.pue,1.25);assert.equal(c.requiredItMw,10);assert.equal(c.requiredMw,12.5);for(const r of c.results.filter(r=>r.scenario==='base'))assert.equal(r.capacity.annualDemandGpuHours,caseDefaults.annualHours);assert.equal(c.results[0].capacity.peakFacilityMw,25);assert.equal(c.results[0].capacity.gpuCount,c.results[2].capacity.gpuCount)});
test('personal sizing does not change the committee baseline or shared defaults',()=>{const before=JSON.stringify(caseDefaults);const personal=evaluateCase({...caseDefaults,pue:1.5,annualHours:14000000,peakGpus:2500},.0614);const team=evaluateCommitteeCase(caseDefaults,.0614);assert.equal(personal.inputs.itMw,5);assert.equal(team.inputs.itMw,20);assert.equal(team.inputs.pue,1.25);assert.equal(JSON.stringify(caseDefaults),before)});

test('saved team PUE revision changes current energy while preserving course reference',()=>{const c=evaluateCommitteeCase({...caseDefaults,pue:1.3},.0614);assert.equal(c.inputs.itMw,20);assert.equal(c.results[0].capacity.peakFacilityMw,26);assert.equal(c.referenceResults![0].capacity.peakFacilityMw,25)});
