import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseResearchResponse,researchPayload,researchRequest,researchDomains,validateResearchSources} from '../lib/research.ts';
const sample=(url='https://example.edu/policy')=>({status:'completed',output:[{type:'web_search_call',status:'completed'},{type:'message',content:[{type:'output_text',text:'Policy supports quotas. [source]',annotations:[{type:'url_citation',start_index:24,end_index:32,url,title:'Allocation policy'}]}]}]});
test('preserves citation offsets and source provenance',()=>{const [block]=parseResearchResponse(sample());assert.equal(block.text.slice(block.citations[0].start_index,block.citations[0].end_index),'[source]');assert.equal(block.citations[0].url,'https://example.edu/policy');});
test('rejects generated answers without completed search or citations',()=>{const raw=sample();raw.output.shift();assert.throws(()=>parseResearchResponse(raw));const uncited=sample();uncited.output[1].content![0].annotations=[];assert.throws(()=>parseResearchResponse(uncited));assert.throws(()=>parseResearchResponse({...sample(),status:'incomplete'}));});
test('rejects unsafe links and invalid citation ranges',()=>{assert.throws(()=>parseResearchResponse(sample('javascript:alert(1)')));const raw=sample();raw.output[1].content![0].annotations[0].end_index=999;assert.throws(()=>parseResearchResponse(raw));});
test('forces live search and validates bounded topic inputs',()=>{const req={topic:'governance' as const,route:'lease' as const,question:'Find shared HPC allocation policies.'};assert.equal(researchRequest.safeParse(req).success,true);assert.equal(researchRequest.safeParse({...req,question:'a'.repeat(1201)}).success,false);const payload=researchPayload(req,'gpt-4.1-mini');assert.equal(payload.tool_choice,'required');assert.equal(payload.tools[0].external_web_access,true);assert.match(payload.input,/lease/);assert.equal(payload.store,false);});
test('grid research carries the selected country and rejects unsupported contexts',()=>{const req=researchRequest.parse({topic:'grid',route:'hybrid',country:'SE',question:'How does this affect other grid customers?'});const payload=researchPayload(req,'gpt-4.1-mini');assert.match(payload.input,/Sweden/);assert.match(payload.input,/grid customers/);assert.doesNotMatch(payload.input,/Paris-Saclay/);assert.equal(researchRequest.safeParse({...req,country:'XX'}).success,false);});

test('grid evidence stays on selected official domains and rejects secondary media',()=>{assert.ok(researchDomains('grid','FR').includes('rte-france.com'));assert.ok(!researchDomains('grid','SE').includes('rte-france.com'));assert.equal(validateResearchSources(parseResearchResponse(sample('https://www.rte-france.com/report')),'grid','FR'),true);assert.equal(validateResearchSources(parseResearchResponse(sample('https://rte-france.com.fake.test/report')),'grid','FR'),false);});
test('compact cards preserve citation positions and require four short sections',async()=>{const {compactResearchSections}=await import('../lib/research.ts');const text='Proposed decision\nRetain ownership.\nRationale\nCase assumption: mixed workloads.\nEvidence\nAn official example. [1]\nUnknowns\nContracts remain unconfirmed.';const start=text.indexOf('[1]');const blocks=[{text,citations:[{type:'url_citation' as const,start_index:start,end_index:start+3,url:'https://www.genci.fr/example',title:'Example'}]}];const sections=compactResearchSections(blocks);assert.equal(sections.length,4);const c=sections[2].block.citations[0];assert.equal(sections[2].block.text.slice(c.start_index,c.end_index),'[1]');assert.throws(()=>compactResearchSections([{text:text.replace('Unknowns','Conclusion'),citations:[]} ]));assert.throws(()=>compactResearchSections([{text:text+' extra'.repeat(180),citations:[]} ]));assert.equal(compactResearchSections([{text:text.replace('An official example. [1]','No relevant external evidence found.'),citations:[]}]).length,4);});
